spring:
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: network_logs_group
      auto-offset-reset: earliest
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    listener:
      missing-topics-fatal: false
